name: build

on:
  push:
  pull_request:
    branches:    
      - main
      - dev

jobs:
  build_backend:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./jobradoodle/backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm ci
      - run: npm run build
      
  build_frontend:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./jobradoodle/frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm ci
      - run: npm run build
